import type {
  AppState,
  AppUser,
  DispatchDocument,
  DispatchException,
  DispatchRequest,
  InventoryBatch,
  Product,
} from "./types";

export const requiredDocuments: DispatchDocument[] = [
  { type: "COMMERCIAL_INVOICE", present: true, verified: false },
  { type: "DELIVERY_CHALLAN", present: true, verified: false },
  { type: "PACKING_LIST", present: true, verified: false },
  { type: "GATE_PASS", present: true, verified: false },
];

export const demoUsers: AppUser[] = [
  {
    id: "u-dispatch",
    name: "Anita Karki",
    role: "DISPATCH_CLERK",
    department: "Dispatch Office",
  },
  {
    id: "u-quality",
    name: "Ramesh Thapa",
    role: "WAREHOUSE_QUALITY",
    department: "Warehouse and Quality",
  },
  {
    id: "u-supervisor",
    name: "Sanjay Gupta",
    role: "DISPATCH_SUPERVISOR",
    department: "Dispatch Control",
  },
  {
    id: "u-gate",
    name: "Mina Tamang",
    role: "GATE_SECURITY",
    department: "Factory Gate",
  },
  {
    id: "u-admin",
    name: "Prakash Adhikari",
    role: "MANAGER_ADMIN",
    department: "Operations Management",
  },
];

export const demoProducts: Product[] = [
  {
    code: "PR-120-KRAFT",
    name: "Kraft Liner Reel",
    productType: "PAPER_REEL",
    unit: "KG",
    gsm: 120,
    grade: "KLB",
    shade: "Natural Brown",
    size: "1450 mm reel",
  },
  {
    code: "PR-180-WB",
    name: "White Board Reel",
    productType: "PAPER_REEL",
    unit: "KG",
    gsm: 180,
    grade: "Duplex",
    shade: "White Back",
    size: "1220 mm reel",
  },
  {
    code: "SR-75-MAP",
    name: "Maplitho Sheet Ream",
    productType: "SHEET_REAM",
    unit: "REAM",
    gsm: 75,
    grade: "Writing/Printing",
    shade: "Bright White",
    size: "A4 ream",
  },
  {
    code: "SR-90-LEDGER",
    name: "Ledger Sheet Ream",
    productType: "SHEET_REAM",
    unit: "REAM",
    gsm: 90,
    grade: "Ledger",
    shade: "Creamwove",
    size: "Legal ream",
  },
];

export const demoInventory: InventoryBatch[] = [
  {
    id: "b-kraft-001",
    batchNo: "KLB-26-0715-A",
    productCode: "PR-120-KRAFT",
    productName: "Kraft Liner Reel",
    productType: "PAPER_REEL",
    unit: "KG",
    onHandQty: 18000,
    reservedQty: 4200,
    qualityStatus: "RELEASED",
    location: "FG Reel Bay A1",
    gsm: 120,
    grade: "KLB",
    shade: "Natural Brown",
    size: "1450 mm reel",
    producedOn: "2026-07-12",
  },
  {
    id: "b-kraft-002",
    batchNo: "KLB-26-0714-B",
    productCode: "PR-120-KRAFT",
    productName: "Kraft Liner Reel",
    productType: "PAPER_REEL",
    unit: "KG",
    onHandQty: 5600,
    reservedQty: 0,
    qualityStatus: "BLOCKED",
    location: "Quality Hold Q2",
    gsm: 120,
    grade: "KLB",
    shade: "Natural Brown",
    size: "1450 mm reel",
    producedOn: "2026-07-14",
  },
  {
    id: "b-white-001",
    batchNo: "DUP-26-0713-C",
    productCode: "PR-180-WB",
    productName: "White Board Reel",
    productType: "PAPER_REEL",
    unit: "KG",
    onHandQty: 11800,
    reservedQty: 0,
    qualityStatus: "RELEASED",
    location: "FG Reel Bay B3",
    gsm: 180,
    grade: "Duplex",
    shade: "White Back",
    size: "1220 mm reel",
    producedOn: "2026-07-13",
  },
  {
    id: "b-map-001",
    batchNo: "MAP-26-0710-A",
    productCode: "SR-75-MAP",
    productName: "Maplitho Sheet Ream",
    productType: "SHEET_REAM",
    unit: "REAM",
    onHandQty: 3200,
    reservedQty: 800,
    qualityStatus: "RELEASED",
    location: "Sheet Store S1",
    gsm: 75,
    grade: "Writing/Printing",
    shade: "Bright White",
    size: "A4 ream",
    producedOn: "2026-07-10",
  },
  {
    id: "b-map-002",
    batchNo: "MAP-26-0715-H",
    productCode: "SR-75-MAP",
    productName: "Maplitho Sheet Ream",
    productType: "SHEET_REAM",
    unit: "REAM",
    onHandQty: 1400,
    reservedQty: 0,
    qualityStatus: "PENDING_INSPECTION",
    location: "Inspection Queue IQ1",
    gsm: 75,
    grade: "Writing/Printing",
    shade: "Bright White",
    size: "A4 ream",
    producedOn: "2026-07-15",
  },
  {
    id: "b-ledger-001",
    batchNo: "LED-26-0709-D",
    productCode: "SR-90-LEDGER",
    productName: "Ledger Sheet Ream",
    productType: "SHEET_REAM",
    unit: "REAM",
    onHandQty: 950,
    reservedQty: 0,
    qualityStatus: "RELEASED",
    location: "Sheet Store S2",
    gsm: 90,
    grade: "Ledger",
    shade: "Creamwove",
    size: "Legal ream",
    producedOn: "2026-07-09",
  },
];

function exception(
  id: string,
  dispatchId: string,
  code: string,
  message: string,
  severity: "LOW" | "MEDIUM" | "HIGH" = "HIGH",
): DispatchException {
  return {
    id,
    dispatchId,
    code,
    message,
    severity,
    controlStatus: severity === "LOW" ? "WARNING" : "BLOCKED",
    createdAt: "2026-07-15T09:30:00+05:45",
  };
}

export const demoDispatches: DispatchRequest[] = [
  {
    id: "d-001",
    requestNo: "FGD-2026-0715-001",
    customerName: "Himalayan Packaging Distributors",
    customerType: "DISTRIBUTOR",
    destination: "Birgunj, Nepal",
    status: "DISPATCHED",
    controlStatus: "CLEAR",
    priority: "NORMAL",
    createdAt: "2026-07-15T08:10:00+05:45",
    requestedDispatchDate: "2026-07-15",
    createdBy: "Anita Karki",
    approvedBy: "Sanjay Gupta",
    lines: [
      {
        id: "l-001",
        productCode: "PR-120-KRAFT",
        productName: "Kraft Liner Reel",
        productType: "PAPER_REEL",
        unit: "KG",
        requestedQty: 4200,
        reservedBatchIds: ["b-kraft-001"],
      },
    ],
    vehicle: {
      vehicleNo: "Na 7 Kha 4481",
      transporter: "Bishal Transport Service",
      driverName: "Bikash Yadav",
      driverPhone: "9800000145",
      expectedArrival: "2026-07-15T10:00:00+05:45",
    },
    documents: requiredDocuments.map((doc) => ({ ...doc, verified: true })),
    expectedWeightKg: 4200,
    actualWeightKg: 4245,
    weightTolerancePercent: 1.5,
    exceptions: [],
    audit: [
      {
        id: "a-001",
        dispatchId: "d-001",
        at: "2026-07-15T08:10:00+05:45",
        actor: "Anita Karki",
        role: "DISPATCH_CLERK",
        action: "CREATED",
        toStatus: "DRAFT",
        note: "Dispatch request created from approved customer order.",
      },
      {
        id: "a-002",
        dispatchId: "d-001",
        at: "2026-07-15T09:20:00+05:45",
        actor: "Sanjay Gupta",
        role: "DISPATCH_SUPERVISOR",
        action: "APPROVED_AND_RESERVED",
        fromStatus: "AWAITING_APPROVAL",
        toStatus: "APPROVED",
        note: "Released inventory reserved from batch KLB-26-0715-A.",
      },
      {
        id: "a-003",
        dispatchId: "d-001",
        at: "2026-07-15T12:40:00+05:45",
        actor: "Mina Tamang",
        role: "GATE_SECURITY",
        action: "EXIT_CONFIRMED",
        fromStatus: "CLEARED_FOR_EXIT",
        toStatus: "DISPATCHED",
        note: "Vehicle exited gate; inventory deducted.",
      },
    ],
  },
  {
    id: "d-002",
    requestNo: "FGD-2026-0715-002",
    customerName: "Ganga Paper Wholesalers",
    customerType: "WHOLESALER",
    destination: "Patna, India",
    status: "REJECTED",
    controlStatus: "BLOCKED",
    priority: "URGENT",
    createdAt: "2026-07-15T09:00:00+05:45",
    requestedDispatchDate: "2026-07-15",
    createdBy: "Anita Karki",
    lines: [
      {
        id: "l-002",
        productCode: "SR-90-LEDGER",
        productName: "Ledger Sheet Ream",
        productType: "SHEET_REAM",
        unit: "REAM",
        requestedQty: 1400,
        reservedBatchIds: [],
      },
    ],
    documents: requiredDocuments.map((doc) => ({ ...doc })),
    weightTolerancePercent: 1.5,
    exceptions: [
      exception(
        "e-002",
        "d-002",
        "INSUFFICIENT_RELEASED_STOCK",
        "Requested 1,400 REAM, but only 950 REAM released stock is available.",
      ),
    ],
    audit: [
      {
        id: "a-004",
        dispatchId: "d-002",
        at: "2026-07-15T09:00:00+05:45",
        actor: "Anita Karki",
        role: "DISPATCH_CLERK",
        action: "CREATED",
        toStatus: "DRAFT",
        note: "Urgent wholesale dispatch entered.",
      },
      {
        id: "a-005",
        dispatchId: "d-002",
        at: "2026-07-15T09:04:00+05:45",
        actor: "System Control",
        role: "MANAGER_ADMIN",
        action: "VALIDATION_REJECTED",
        fromStatus: "DRAFT",
        toStatus: "REJECTED",
        note: "Insufficient released stock blocked approval.",
      },
    ],
  },
  {
    id: "d-003",
    requestNo: "FGD-2026-0715-003",
    customerName: "Eastern Corrugators Pvt. Ltd.",
    customerType: "COMMERCIAL",
    destination: "Bhairahawa, Nepal",
    status: "REJECTED",
    controlStatus: "BLOCKED",
    priority: "NORMAL",
    createdAt: "2026-07-15T09:25:00+05:45",
    requestedDispatchDate: "2026-07-16",
    createdBy: "Anita Karki",
    lines: [
      {
        id: "l-003",
        productCode: "PR-120-KRAFT",
        productName: "Kraft Liner Reel",
        productType: "PAPER_REEL",
        unit: "KG",
        requestedQty: 5200,
        reservedBatchIds: ["b-kraft-002"],
      },
    ],
    documents: requiredDocuments.map((doc) => ({ ...doc })),
    weightTolerancePercent: 1.5,
    exceptions: [
      exception(
        "e-003",
        "d-003",
        "QUALITY_BLOCKED_BATCH",
        "Batch KLB-26-0714-B is quality blocked and cannot be dispatched.",
      ),
    ],
    audit: [
      {
        id: "a-006",
        dispatchId: "d-003",
        at: "2026-07-15T09:25:00+05:45",
        actor: "Ramesh Thapa",
        role: "WAREHOUSE_QUALITY",
        action: "QUALITY_BLOCK",
        toStatus: "REJECTED",
        note: "Requested batch is on quality hold.",
      },
    ],
  },
  {
    id: "d-004",
    requestNo: "FGD-2026-0715-004",
    customerName: "Kathmandu Print & Pack",
    customerType: "COMMERCIAL",
    destination: "Kathmandu, Nepal",
    status: "AWAITING_WEIGHT_CHECK",
    controlStatus: "BLOCKED",
    priority: "NORMAL",
    createdAt: "2026-07-15T07:35:00+05:45",
    requestedDispatchDate: "2026-07-15",
    createdBy: "Anita Karki",
    approvedBy: "Sanjay Gupta",
    lines: [
      {
        id: "l-004",
        productCode: "PR-180-WB",
        productName: "White Board Reel",
        productType: "PAPER_REEL",
        unit: "KG",
        requestedQty: 5000,
        reservedBatchIds: ["b-white-001"],
      },
    ],
    vehicle: {
      vehicleNo: "Ba 5 Kha 2390",
      transporter: "Sagarmatha Logistics",
      driverName: "Suman Rai",
      driverPhone: "9811112233",
      expectedArrival: "2026-07-15T11:30:00+05:45",
    },
    documents: requiredDocuments.map((doc) => ({ ...doc, verified: true })),
    expectedWeightKg: 5000,
    actualWeightKg: 5126,
    weightTolerancePercent: 1.5,
    exceptions: [
      exception(
        "e-004",
        "d-004",
        "WEIGHT_VARIANCE_EXCEEDED",
        "Actual weight variance is 2.52%, above the approved 1.5% tolerance.",
      ),
    ],
    audit: [
      {
        id: "a-007",
        dispatchId: "d-004",
        at: "2026-07-15T12:10:00+05:45",
        actor: "Ramesh Thapa",
        role: "WAREHOUSE_QUALITY",
        action: "WEIGHT_CHECK_BLOCKED",
        fromStatus: "LOADING",
        toStatus: "AWAITING_WEIGHT_CHECK",
        note: "Weight variance requires supervisor review before document check.",
      },
    ],
  },
  {
    id: "d-005",
    requestNo: "FGD-2026-0715-005",
    customerName: "Janakpur Stationery Traders",
    customerType: "DISTRIBUTOR",
    destination: "Janakpur, Nepal",
    status: "AWAITING_DOCUMENT_CHECK",
    controlStatus: "BLOCKED",
    priority: "NORMAL",
    createdAt: "2026-07-15T08:40:00+05:45",
    requestedDispatchDate: "2026-07-15",
    createdBy: "Anita Karki",
    approvedBy: "Sanjay Gupta",
    lines: [
      {
        id: "l-005",
        productCode: "SR-75-MAP",
        productName: "Maplitho Sheet Ream",
        productType: "SHEET_REAM",
        unit: "REAM",
        requestedQty: 800,
        reservedBatchIds: ["b-map-001"],
      },
    ],
    vehicle: {
      vehicleNo: "Pra 2-03-001 Kha 8842",
      transporter: "Madhesh Carrier",
      driverName: "Ajay Sah",
      driverPhone: "9844448877",
      expectedArrival: "2026-07-15T13:00:00+05:45",
    },
    documents: [
      { type: "COMMERCIAL_INVOICE", present: true, verified: true },
      { type: "DELIVERY_CHALLAN", present: true, verified: true },
      { type: "PACKING_LIST", present: false, verified: false },
      { type: "GATE_PASS", present: true, verified: false },
    ],
    expectedWeightKg: 0,
    weightTolerancePercent: 1.5,
    exceptions: [
      exception(
        "e-005",
        "d-005",
        "MISSING_DOCUMENT",
        "Packing list is missing; gate clearance is blocked.",
      ),
    ],
    audit: [
      {
        id: "a-008",
        dispatchId: "d-005",
        at: "2026-07-15T13:30:00+05:45",
        actor: "Sanjay Gupta",
        role: "DISPATCH_SUPERVISOR",
        action: "DOCUMENT_CHECK_BLOCKED",
        fromStatus: "AWAITING_WEIGHT_CHECK",
        toStatus: "AWAITING_DOCUMENT_CHECK",
        note: "Packing list not attached.",
      },
    ],
  },
  {
    id: "d-006",
    requestNo: "FGD-2026-0715-006",
    customerName: "Lumbini Box Industries",
    customerType: "COMMERCIAL",
    destination: "Butwal, Nepal",
    status: "AWAITING_APPROVAL",
    controlStatus: "CLEAR",
    priority: "NORMAL",
    createdAt: "2026-07-15T10:15:00+05:45",
    requestedDispatchDate: "2026-07-16",
    createdBy: "Anita Karki",
    lines: [
      {
        id: "l-006",
        productCode: "PR-180-WB",
        productName: "White Board Reel",
        productType: "PAPER_REEL",
        unit: "KG",
        requestedQty: 2800,
        reservedBatchIds: [],
      },
    ],
    documents: requiredDocuments.map((doc) => ({ ...doc })),
    expectedWeightKg: 2800,
    weightTolerancePercent: 1.5,
    exceptions: [],
    audit: [
      {
        id: "a-009",
        dispatchId: "d-006",
        at: "2026-07-15T10:15:00+05:45",
        actor: "Anita Karki",
        role: "DISPATCH_CLERK",
        action: "SUBMITTED",
        fromStatus: "DRAFT",
        toStatus: "AWAITING_APPROVAL",
        note: "Released stock available. Awaiting dispatch supervisor approval.",
      },
    ],
  },
];

export const initialState: AppState = {
  users: demoUsers,
  products: demoProducts,
  inventory: demoInventory,
  dispatches: demoDispatches,
};
